# Generated by Django 6.0.1 on 2026-03-04 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grestmanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='managed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default='cerutti', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='vat_number',
            field=models.CharField(default='ABCDFG89D01L157Y', max_length=200),
            preserve_default=False,
        ),
    ]
