# Generated by Django 6.0.1 on 2026-03-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grestmanager', '0002_remove_subscription_user_person_managed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('subscription_opening_date', models.DateTimeField(verbose_name='subscription opening date')),
                ('subscription_closing_date', models.DateTimeField(verbose_name='subscription closing date')),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='vat_number',
            new_name='tax_code',
        ),
        migrations.AddField(
            model_name='subscription',
            name='to_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='grestmanager.event'),
            preserve_default=False,
        ),
    ]
