# Generated by Django 6.0.1 on 2026-03-30 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grestmanager', '0003_event_rename_vat_number_person_tax_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='related_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='grestmanager.person'),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], default='IN', max_length=3)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='grestmanager.person')),
            ],
        ),
    ]
