# Generated by Django 6.0.1 on 2026-06-10 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grestmanager', '0004_alter_subscription_related_to_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='to_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='grestmanager.event', verbose_name='Evento'),
            preserve_default=False,
        ),
    ]
