# Generated by Django 6.0.1 on 2026-06-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grestmanager', '0006_remove_subscription_price_event_price_afternoon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price_trip',
        ),
        migrations.AddField(
            model_name='event',
            name='price_trip_week1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='price_trip_week2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='price_trip_week3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='price_trip_week4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
